[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.mbstring", "php83Extensions.gd", "php83Extensions.curl"]

[phases.install]
cmds = ["mkdir -p /etc/php"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t ."
