[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo", "php83Extensions.pdo_mysql", "php83Extensions.mysqli", "php83Extensions.mbstring", "php83Extensions.gd"]

[start]
cmd = "php -c php.ini -S 0.0.0.0:${PORT:-8080} -t ."
